export const QUOTES = [
'Get busy living or get busy dying.',
'The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.',
'When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.',
'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do.',
'When I dare to be powerful – to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.',
'A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow. ',
'Great minds discuss ideas; average minds discuss events; small minds discuss people.',
'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.',
'Those who dare to fail miserably can achieve greatly.',
'I can’t give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.',
'You only live once, but if you do it right, once is enough. ',
'Would you like me to give you a formula for success? It’s quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that’s where you will find success.',
'He that falls in love with himself will have no rivals.',
'It is hard to fail, but it is worse never to have tried to succeed.',
'I’m a success today because I had a friend who believed in me and I didn’t have the heart to let him down.',
'Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world.',
'Let us always meet each other with smile, for the smile is the beginning of love.',
'Challenges are what make life interesting and overcoming them is what makes life meaningful.',
'When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one that has opened for us.',
'Love is a serious mental disease.',
'Our greatest fear should not be of failure… but of succeeding at things in life that don’t really matter.',
'It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.',
'Remember that the happiest people are not those getting more, but those giving more.',
'The only impossible journey is the one you never begin.',
'It is our choices, that show what we truly are, far more than our abilities.',
'Only put off until tomorrow what you are willing to die having left undone.',
'If you want to be happy, be.',
'Many of life’s failures are people who did not realize how close they were to success when they gave up.',
'If you want to live a happy life, tie it to a goal, not to people or things.',
'Success is just a war of attrition. Sure, there’s an element of talent you should probably possess. But if you just stick around long enough, eventually something is going to happen.',
'The opposite of love is not hate; it’s indifference.',
'Life is ten percent what happens to you and ninety percent how you respond to it.',
'The good news is that the moment you decide that what you know is more important than what you have been taught to believe, you will have shifted gears in your quest for abundance. Success comes from within, not from without.',
'I never knew how to worship until I knew how to love.',
'Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.',
'It is impossible to escape the impression that people commonly use false standards of measurement — that they seek power, success and wealth for themselves and admire them in others, and that they underestimate what is of true value in life.',
'A friend is someone who gives you total freedom to be yourself.',
'All that we see and seem is but a dream within a dream.',
'Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.',
'Never let the fear of striking out keep you from playing the game.',
'Live in the sunshine, swim the sea, drink the wild air.',
'Life is trying things to see if they work.',
'Success in business requires training and discipline and hard work. But if you’re not frightened by these things, the opportunities are just as great today as they ever were.',
'The purpose of our lives is to be happy.',
'The No. 1 reason people fail in life is because they listen to their friends, family, and neighbors.',
'Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking.',
'Success is how high you bounce when you hit bottom.',
'You will face many defeats in life, but never let yourself be defeated.',
'May you live all the days of your life.',
'In three words I can sum up everything I’ve learned about life: It goes on.',
'Success is not final, failure is not fatal: it is the courage to continue that counts.',
'You’re not obligated to win. You’re obligated to keep trying. To the best you can do everyday.',
'If life were predictable it would cease to be life, and be without flavor.',
'If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.',
'The question isn’t who is going to let me; it’s who is going to stop me.',
'Life is like a box of chocolates. You never know what you’re going to get.',
'The three great essentials to achieve anything worthwhile are, first, hard work; second, stick-to-itiveness; third, common sense.',
'The successful warrior is the average man, with laser-like focus.',
'A man is a success if he gets up in the morning and gets to bed at night, and in between he does what he wants to do.',
'Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.',
'Life isn’t about finding yourself. Life is about creating yourself.',
'The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.',
'Success? I don’t know what that word means. I’m happy. But success, that goes back to what in somebody’s eyes success means. For me, success is inner peace. That’s a good day for me.',
'A kiss is a lovely trick designed by nature to stop speech when words become superfluous.',
'You miss 100 percent of the shots you never take.',
'Life itself is the most wonderful fairy tale.”',
'In order to write about life first you must live it.',
'Do not go where the path may lead; go instead where there is no path and leave a trail.',
'We are what we repeatedly do; excellence, then, is not an act but a habit.',
'Always forgive your enemies; nothing annoys them so much.',
'The big lesson in life, baby, is never be scared of anyone or anything.',
'If you aren’t going all the way, why go at all?',
'To love and be loved is to feel the sun from both sides.',
'Love is an irresistible desire to be irresistibly desired.',
'Those who believe in telekinetics, raise my hand.',
'I only regret that I have but one life to give for my country.',
'The person who reads too much and uses his brain too little will fall into lazy habits of thinking.',
'Life would be tragic if it weren’t funny.',
'Better to have loved and lost, than to have never loved at all.',
'Every child is an artist, the problem is staying an artist when you grow up.',
'Have no fear of perfection, you’ll never reach it.',
'Life is not a problem to be solved, but a reality to be experienced.',
'Curiosity about life in all of its aspects, I think, is still the secret of great creative people.',
'Be yourself; everyone else is already taken.',
'Imagination is the beginning of creation. You imagine what you desire, you will what you imagine, and at last, you create what you will.',
'The journey of a thousand miles begins with one step.',
'Imagination was given to man to compensate him for what he is not, and a sense of humor was provided to console him for what he is.',
'What you do speaks so loudly that I cannot hear what you say.',
'Spread love everywhere you go: first of all in your own house. Give love to your children, to your wife or husband, to a next door neighbor. Let no one ever come to you without leaving better and happier. Be the living expression of God’s kindness; kindness in your face, kindness in your eyes, kindness in your smile, kindness in your warm greeting.',
'Be happy for this moment. This moment is your life.',
'You must be the change you wish to see in the world.',
'Strive not to be a success, but rather to be of value.',
'Keep your face to the sunshine and you can never see the shadow.',
'The best way out is always through.',
'The dream crossed twilight between birth and dying.',
'People are just as happy as they make up their minds to be.',
'Don’t think. Thinking is the enemy of creativity. It’s self-conscious, and anything self-conscious is lousy. You can’t try to do things. You simply must do things.',
'Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn’t really do it, the just saw something. It seemed obvious to them after a while.',
'Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.',
'The power of imagination makes us infinite.',
'Doing the best at this moment puts you in the best place for the next moment.',
'Originality is nothing but judicious imitation.',
'Life is made of ever so many partings welded together.',
];

export const AUTHORS = [
'Stephen King',
'Mark Caine',
'Helen Keller',
'Mark Twain',
'Audre Lorde',
'William Shakespeare',
'Eleanor Roosevelt',
'David Brinkley',
'John F. Kennedy',
'Herbert Bayard Swope',
'Mae West',
'Thomas J. Watson',
'Benjamin Franklin',
'Theodore Roosevelt',
'Abraham Lincoln',
'Lucille Ball',
'Mother Theresa',
'Joshua J. Marine',
'Alexander Graham Bell',
'Plato',
'Francis Chan',
'Leonardo Da Vinci',
'H. Jackson Brown, Jr.',
'Anthony Robbins',
'J. K Rowling',
'Pablo Picasso',
'Leo Tolstoy',
'Thomas A. Edison',
'Albert Einstein',
'Dax Shepard',
'Elie Wiesel',
'Charles Swindoll',
'Elie Wiesel',
'Henry Ward Beecher',
'Harriet Tubman',
'Sigmund Freud',
'Jim Morrison',
'Edgar Allan Poe',
'Harriet Tubman',
'Babe Ruth',
'Ralph Waldo Emerson',
'Ray Bradbury',
'David Rockefeller',
'Dalai Lama',
'Napoleon Hill',
'Steve Jobs',
'George S. Patton',
'Maya Angelou',
'Jonathan Swift',
'Robert Frost',
'Winston Churchill',
'Jason Mraz',
'Eleanor Roosevelt',
'Jim Rohn',
'Ayn Rand',
'Forrest Gump',
'Thomas A. Edison',
'Bruce Lee',
'Bob Dylan',
'Bil Keane',
'George Bernard Shaw',
'Henry Ford',
'Denzel Washington',
'Ingrid Bergman',
'Wayne Gretzky',
'Hans Christian Andersen',
'Ernest Hemingway',
'Ralph Waldo Emerson',
'Aristotle',
'Oscar Wilde',
'Frank Sinatra',
'Joe Namath',
'David Viscott',
'Robern Frost',
'Kurt Vonnegut',
'Nathan Hale',
'Albert Einstein',
'Stephen Hawking',
'St. Augustine',
'Pablo Picasso',
'Salvador Dali',
'Søren Kierkegaard',
'Leo Burnett',
'Oscar Wilde',
'George Bernard Shaw',
'Lao Tzu',
'Oscar Wilde',
'Ralph Waldo Emerson',
'Mother Theresa',
'Omar Khayyam',
'Gandhi',
'Albert Einstein',
'Helen Keller',
'Robern Frost',
'T. S. Eliot',
'Abraham Lincoln',
'Ray Bradbury',
'Steve Jobs',
'Mark Twain',
'John Muir',
'Oprah Winfrey',
'Voltaire',
'Charles Dickens',
];